RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

